"""create leads table

Revision ID: 23f9b4ac12a0
Revises: b0b772876ded
Create Date: 2025-11-26 10:07:56.133561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23f9b4ac12a0'
down_revision: Union[str, Sequence[str], None] = 'b0b772876ded'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads',
    sa.Column('lead_id', sa.String(), nullable=False),
    sa.Column('cnpj', sa.String(), nullable=False),
    sa.Column('enterprise_name', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('declared_state', sa.String(), nullable=False),
    sa.Column('declared_city', sa.String(), nullable=False),
    sa.Column('declared_segment', sa.String(), nullable=False),
    sa.Column('cnpj_state', sa.String(), nullable=True),
    sa.Column('cnpj_city', sa.String(), nullable=True),
    sa.Column('cnpj_segment', sa.String(), nullable=True),
    sa.Column('divergences', sa.JSON(), nullable=True),
    sa.Column('assigned_vendor_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('lead_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('leads')
    # ### end Alembic commands ###
